# Generated by Django 4.2.24 on 2025-10-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webfeatureservice',
            name='version',
            field=models.CharField(choices=[('1.0.0', 'V 1 0 0'), ('1.1.0', 'V 1 1 0'), ('1.1.1', 'V 1 1 1'), ('1.3.0', 'V 1 3 0'), ('2.0.0', 'V 2 0 0'), ('2.0.2', 'V 2 0 2')], default='2.0.0', editable=False, help_text='the version of the service type as sem version', max_length=10, verbose_name='version'),
            preserve_default=False,
        ),
    ]
