# Generated by Django 4.2.24 on 2025-10-10 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import update_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('update_app', '0002_webfeatureservice_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='webfeatureservice',
            name='xml_backup_file',
            field=models.FileField(default='update_app/files/fixture_2.0.0.xml', editable=False, help_text='the original xml as backup to restore the xml field.', upload_to=update_app.models.xml_backup_file_path, verbose_name='xml backup'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistoricalWebFeatureService',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('xml_backup_file', models.TextField(editable=False, help_text='the original xml as backup to restore the xml field.', max_length=100, verbose_name='xml backup')),
                ('version', models.CharField(choices=[('1.0.0', 'V 1 0 0'), ('1.1.0', 'V 1 1 0'), ('1.1.1', 'V 1 1 1'), ('1.3.0', 'V 1 3 0'), ('2.0.0', 'V 2 0 0'), ('2.0.2', 'V 2 0 2')], editable=False, help_text='the version of the service type as sem version', max_length=10, verbose_name='version')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical web feature service',
                'verbose_name_plural': 'historical web feature services',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
