# Generated by Django 4.2.24 on 2025-10-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_app', '0003_webfeatureservice_xml_backup_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebfeatureservice',
            name='abstract',
            field=models.TextField(blank=True, default='', help_text='brief summary of the content of this metadata.', verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='historicalwebfeatureservice',
            name='title',
            field=models.CharField(default='', help_text='a short descriptive title for this metadata', max_length=1000, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='webfeatureservice',
            name='abstract',
            field=models.TextField(blank=True, default='', help_text='brief summary of the content of this metadata.', verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='webfeatureservice',
            name='title',
            field=models.CharField(default='', help_text='a short descriptive title for this metadata', max_length=1000, verbose_name='title'),
        ),
    ]
