# Generated by Django 4.2.24 on 2025-10-29 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import simple_history.models
import update_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('update_app', '0004_historicalwebfeatureservice_abstract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', help_text='a short descriptive title for this metadata', max_length=1000, verbose_name='title')),
                ('abstract', models.TextField(blank=True, default='', help_text='brief summary of the content of this metadata.', verbose_name='abstract')),
            ],
        ),
        migrations.CreateModel(
            name='WebMapService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_backup_file', models.FileField(editable=False, help_text='the original xml as backup to restore the xml field.', upload_to=update_app.models.xml_backup_file_path, verbose_name='xml backup')),
                ('version', models.CharField(choices=[('1.0.0', 'V 1 0 0'), ('1.1.0', 'V 1 1 0'), ('1.1.1', 'V 1 1 1'), ('1.3.0', 'V 1 3 0'), ('2.0.0', 'V 2 0 0'), ('2.0.2', 'V 2 0 2')], editable=False, help_text='the version of the service type as sem version', max_length=10, verbose_name='version')),
                ('title', models.CharField(default='', help_text='a short descriptive title for this service', max_length=1000, verbose_name='title')),
                ('abstract', models.TextField(blank=True, default='', help_text='brief summary of the content of this service', verbose_name='abstract')),
            ],
        ),
        migrations.AlterField(
            model_name='historicalwebfeatureservice',
            name='abstract',
            field=models.TextField(blank=True, default='', help_text='brief summary of the content of this service', verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='historicalwebfeatureservice',
            name='title',
            field=models.CharField(default='', help_text='a short descriptive title for this service', max_length=1000, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='webfeatureservice',
            name='abstract',
            field=models.TextField(blank=True, default='', help_text='brief summary of the content of this service', verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='webfeatureservice',
            name='title',
            field=models.CharField(default='', help_text='a short descriptive title for this service', max_length=1000, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(default='', help_text='a short descriptive title for this metadata', max_length=1000, verbose_name='title')),
                ('abstract', models.TextField(blank=True, default='', help_text='brief summary of the content of this metadata.', verbose_name='abstract')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('WebMapService', models.ForeignKey(editable=False, help_text='the WMS where this layer is part of', on_delete=django.db.models.deletion.CASCADE, to='update_app.webmapservice', verbose_name='service')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='update_app.layer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalWebMapService',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('xml_backup_file', models.TextField(editable=False, help_text='the original xml as backup to restore the xml field.', max_length=100, verbose_name='xml backup')),
                ('version', models.CharField(choices=[('1.0.0', 'V 1 0 0'), ('1.1.0', 'V 1 1 0'), ('1.1.1', 'V 1 1 1'), ('1.3.0', 'V 1 3 0'), ('2.0.0', 'V 2 0 0'), ('2.0.2', 'V 2 0 2')], editable=False, help_text='the version of the service type as sem version', max_length=10, verbose_name='version')),
                ('title', models.CharField(default='', help_text='a short descriptive title for this service', max_length=1000, verbose_name='title')),
                ('abstract', models.TextField(blank=True, default='', help_text='brief summary of the content of this service', verbose_name='abstract')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical web map service',
                'verbose_name_plural': 'historical web map services',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
