# Generated by Django 4.2.24 on 2025-10-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_app', '0005_featuretype_webmapservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
