# Generated by Django 4.2.24 on 2025-11-03 09:58

from django.db import migrations, models
import django.db.models.deletion
import update_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('update_app', '0006_historicalwebmapservice_name_webmapservice_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The name of the organization', max_length=256, verbose_name='Name')),
                ('person_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Contact person')),
                ('email', models.EmailField(default='', max_length=100, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, default='', max_length=100, verbose_name='Phone')),
                ('facsimile', models.CharField(blank=True, default='', max_length=100, verbose_name='Facsimile')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(default='', max_length=100, verbose_name='Postal code')),
                ('address_type', models.CharField(default='', max_length=100, verbose_name='Address type')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Address')),
                ('state_or_province', models.CharField(default='', max_length=100, verbose_name='State or province')),
                ('country', models.CharField(default='', max_length=100, verbose_name='Country')),
            ],
        ),
        migrations.AlterField(
            model_name='historicalwebmapservice',
            name='version',
            field=models.CharField(choices=[('1.0.0', 'V 1 0 0'), ('1.1.0', 'V 1 1 0'), ('1.1.1', 'V 1 1 1'), ('1.3.0', 'V 1 3 0'), ('2.0.0', 'V 2 0 0'), ('2.0.2', 'V 2 0 2')], default='', editable=False, help_text='the version of the service type as sem version', max_length=10, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='historicalwebmapservice',
            name='xml_backup_file',
            field=models.TextField(default='', editable=False, help_text='the original xml as backup to restore the xml field.', max_length=100, verbose_name='xml backup'),
        ),
        migrations.AlterField(
            model_name='webmapservice',
            name='version',
            field=models.CharField(choices=[('1.0.0', 'V 1 0 0'), ('1.1.0', 'V 1 1 0'), ('1.1.1', 'V 1 1 1'), ('1.3.0', 'V 1 3 0'), ('2.0.0', 'V 2 0 0'), ('2.0.2', 'V 2 0 2')], default='', editable=False, help_text='the version of the service type as sem version', max_length=10, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='webmapservice',
            name='xml_backup_file',
            field=models.FileField(default='', editable=False, help_text='the original xml as backup to restore the xml field.', upload_to=update_app.models.xml_backup_file_path, verbose_name='xml backup'),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='metadata_contact',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='This is the contact for the service provider.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='update_app.metadatacontact', verbose_name='service contact'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='metadata_contact',
            field=models.ForeignKey(blank=True, help_text='This is the contact for the service provider.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_contact', to='update_app.metadatacontact', verbose_name='service contact'),
        ),
    ]
