# Generated by Django 4.2.24 on 2025-11-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_app', '0007_metadatacontact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadatacontact',
            old_name='name',
            new_name='contact_name',
        ),
        migrations.RemoveField(
            model_name='historicalwebmapservice',
            name='metadata_contact',
        ),
        migrations.RemoveField(
            model_name='webmapservice',
            name='metadata_contact',
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='address_type',
            field=models.CharField(default='', max_length=100, verbose_name='Address type'),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='contact_name',
            field=models.CharField(default='', help_text='The name of the organization', max_length=256, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='facsimile',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Facsimile'),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='person_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Contact person'),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='postal_code',
            field=models.CharField(default='', max_length=100, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='state_or_province',
            field=models.CharField(default='', max_length=100, verbose_name='State or province'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='address_type',
            field=models.CharField(default='', max_length=100, verbose_name='Address type'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='contact_name',
            field=models.CharField(default='', help_text='The name of the organization', max_length=256, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='facsimile',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Facsimile'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='person_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Contact person'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='postal_code',
            field=models.CharField(default='', max_length=100, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='state_or_province',
            field=models.CharField(default='', max_length=100, verbose_name='State or province'),
        ),
    ]
