# Generated by Django 4.2.24 on 2025-11-18 13:27

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import update_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('update_app', '0008_rename_name_metadatacontact_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwebmapservice',
            name='xml_backup_file',
            field=models.TextField(help_text='the original xml as backup to restore the xml field.', max_length=100, verbose_name='xml backup'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='WebMapService',
            field=models.ForeignKey(help_text='the WMS where this layer is part of', on_delete=django.db.models.deletion.CASCADE, to='update_app.webmapservice', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='webmapservice',
            name='xml_backup_file',
            field=models.FileField(help_text='the original xml as backup to restore the xml field.', upload_to=update_app.models.xml_backup_file_path, verbose_name='xml backup'),
        ),
        migrations.CreateModel(
            name='TransientLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(default='', help_text='a short descriptive title for this metadata', max_length=1000, verbose_name='title')),
                ('abstract', models.TextField(blank=True, default='', help_text='brief summary of the content of this metadata.', verbose_name='abstract')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='update_app.transientlayer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
